version: "3"
services:
  user-api:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: user-api
    ports:
      - "3000:3000"
    environment:
      - APP_NAME=user-api
      - PORT=3000
      - KAFKA_CLUSTER_NAME=local
      - KAFKA_TOPIC=user
      - KAFKA_BROKERS=43.201.213.254:9092,43.201.213.254:9093,43.201.213.254:9094

  family-api:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: family-api
    ports:
      - "3001:3000"
    environment:
      - APP_NAME=family-api
      - PORT=3000
      - KAFKA_CLUSTER_NAME=local
      - KAFKA_TOPIC=family
      - KAFKA_BROKERS=43.201.213.254:9092,43.201.213.254:9093,43.201.213.254:9094

  coworker-api:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: coworker-api
    ports:
      - "3002:3000"
    environment:
      - APP_NAME=coworker-api
      - PORT=3000
      - KAFKA_CLUSTER_NAME=local
      - KAFKA_TOPIC=coworker
      - KAFKA_BROKERS=43.201.213.254:9092,43.201.213.254:9093,43.201.213.254:9094

  # consumer:
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile
  #   container_name: consumer
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - PORT=8080
  #     - KAFKA_TOPICS=user,family,coworker
  #     - KAFKA_CONSUMER_GROUP=consumer-group
  #     - KAFKA_BROKERS=43.201.213.254:9092,43.201.213.254:9093,43.201.213.254:9094

  consumer-batch:
    build:
      context: ./consumer-batch-listener
      dockerfile: Dockerfile
    container_name: consumer-batch
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - BATCH_SIZE=5
      - KAFKA_TOPICS=user,family,coworker
      # - KAFKA_CONSUMER_GROUP=consumer-donggyu
      - KAFKA_IS_STATIC_MEMBERSHIP=true
      - KAFKA_BROKERS=43.201.213.254:9092,43.201.213.254:9093,43.201.213.254:9094
      - KAFKA_RETRY_COUNT=5
      - KAFKA_BACKOFF=2
